---

- hosts: localhost

  vars_files:
    - vars/main.yml

  handlers:
    - import_tasks: task-lib/handlers.yml

  tasks:

  - block:
    - include_tasks: task-lib/run-xvfb-command.yml
      loop:
        -  mvn clean install -DskipTests
