/*-
 * #%L
 * jgtk
 * %%
 * Copyright (C) 2022 JGTK
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 * 
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */
package com.gitlab.ccook.jgtk.enums;

public enum GtkAccessibleRole {
    GTK_ACCESSIBLE_ROLE_ALERT,
    GTK_ACCESSIBLE_ROLE_ALERT_DIALOG,
    GTK_ACCESSIBLE_ROLE_BANNER,
    GTK_ACCESSIBLE_ROLE_BUTTON,
    GTK_ACCESSIBLE_ROLE_CAPTION,
    GTK_ACCESSIBLE_ROLE_CELL,
    GTK_ACCESSIBLE_ROLE_CHECKBOX,
    GTK_ACCESSIBLE_ROLE_COLUMN_HEADER,
    GTK_ACCESSIBLE_ROLE_COMBO_BOX,
    GTK_ACCESSIBLE_ROLE_COMMAND,
    GTK_ACCESSIBLE_ROLE_COMPOSITE,
    GTK_ACCESSIBLE_ROLE_DIALOG,
    GTK_ACCESSIBLE_ROLE_DOCUMENT,
    GTK_ACCESSIBLE_ROLE_FEED,
    GTK_ACCESSIBLE_ROLE_FORM,
    GTK_ACCESSIBLE_ROLE_GENERIC,
    GTK_ACCESSIBLE_ROLE_GRID,
    GTK_ACCESSIBLE_ROLE_GRID_CELL,
    GTK_ACCESSIBLE_ROLE_GROUP,
    GTK_ACCESSIBLE_ROLE_HEADING,
    GTK_ACCESSIBLE_ROLE_IMG,
    GTK_ACCESSIBLE_ROLE_INPUT,
    GTK_ACCESSIBLE_ROLE_LABEL,
    GTK_ACCESSIBLE_ROLE_LANDMARK,
    GTK_ACCESSIBLE_ROLE_LEGEND,
    GTK_ACCESSIBLE_ROLE_LINK,
    GTK_ACCESSIBLE_ROLE_LIST,
    GTK_ACCESSIBLE_ROLE_LIST_BOX,
    GTK_ACCESSIBLE_ROLE_LIST_ITEM,
    GTK_ACCESSIBLE_ROLE_LOG,
    GTK_ACCESSIBLE_ROLE_MAIN,
    GTK_ACCESSIBLE_ROLE_MARQUEE,
    GTK_ACCESSIBLE_ROLE_MATH,
    GTK_ACCESSIBLE_ROLE_METER,
    GTK_ACCESSIBLE_ROLE_MENU,
    GTK_ACCESSIBLE_ROLE_MENU_BAR,
    GTK_ACCESSIBLE_ROLE_MENU_ITEM,
    GTK_ACCESSIBLE_ROLE_MENU_ITEM_CHECKBOX,
    GTK_ACCESSIBLE_ROLE_MENU_ITEM_RADIO,
    GTK_ACCESSIBLE_ROLE_NAVIGATION,
    GTK_ACCESSIBLE_ROLE_NONE,
    GTK_ACCESSIBLE_ROLE_NOTE,
    GTK_ACCESSIBLE_ROLE_OPTION,
    GTK_ACCESSIBLE_ROLE_PRESENTATION,
    GTK_ACCESSIBLE_ROLE_PROGRESS_BAR,
    GTK_ACCESSIBLE_ROLE_RADIO,
    GTK_ACCESSIBLE_ROLE_RADIO_GROUP,
    GTK_ACCESSIBLE_ROLE_RANGE,
    GTK_ACCESSIBLE_ROLE_REGION,
    GTK_ACCESSIBLE_ROLE_ROW,
    GTK_ACCESSIBLE_ROLE_ROW_GROUP,
    GTK_ACCESSIBLE_ROLE_ROW_HEADER,
    GTK_ACCESSIBLE_ROLE_SCROLLBAR,
    GTK_ACCESSIBLE_ROLE_SEARCH,
    GTK_ACCESSIBLE_ROLE_SEARCH_BOX,
    GTK_ACCESSIBLE_ROLE_SECTION,
    GTK_ACCESSIBLE_ROLE_SECTION_HEAD,
    GTK_ACCESSIBLE_ROLE_SELECT,
    GTK_ACCESSIBLE_ROLE_SEPARATOR,
    GTK_ACCESSIBLE_ROLE_SLIDER,
    GTK_ACCESSIBLE_ROLE_SPIN_BUTTON,
    GTK_ACCESSIBLE_ROLE_STATUS,
    GTK_ACCESSIBLE_ROLE_STRUCTURE,
    GTK_ACCESSIBLE_ROLE_SWITCH,
    GTK_ACCESSIBLE_ROLE_TAB,
    GTK_ACCESSIBLE_ROLE_TABLE,
    GTK_ACCESSIBLE_ROLE_TAB_LIST,
    GTK_ACCESSIBLE_ROLE_TAB_PANEL,
    GTK_ACCESSIBLE_ROLE_TEXT_BOX,
    GTK_ACCESSIBLE_ROLE_TIME,
    GTK_ACCESSIBLE_ROLE_TIMER,
    GTK_ACCESSIBLE_ROLE_TOOLBAR,
    GTK_ACCESSIBLE_ROLE_TOOLTIP,
    GTK_ACCESSIBLE_ROLE_TREE,
    GTK_ACCESSIBLE_ROLE_TREE_GRID,
    GTK_ACCESSIBLE_ROLE_TREE_ITEM,
    GTK_ACCESSIBLE_ROLE_WIDGET,
    GTK_ACCESSIBLE_ROLE_WINDOW;

    public static GtkAccessibleRole getRoleFromCValue(int cValue) {
        return GtkAccessibleRole.values()[cValue];
    }
}
